### ISSUE TITLE
BatchGetOrInsertReq实现

### ISSUE THREAD

**Issue by mutouyuguo** [Loremkang/ThunderSnail#6]

**Comment by Loremkang** [comment]
BatchGetOrInsertReq 包括 key, keylen, hash table id, tuple id 四个组成部分。语义是：
如果当前key在当前hash table中不存在，则将当前tupleid插入到hash table，并返回当前entry的address；
如果当前key在当前hash table中存在，则返回hash table的entry中存储的value，可能是tupleid，也可能是maxlinkaddress
即返回值是 (type, union{HashEntryAddress, TupleId, MaxLinkAddress})
